global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 15s
  repeat_interval: 10m
  receiver: 'webhooks'

receivers:
- name: 'webhooks'
  webhook_configs:
  - url: 'http://192.168.100.112:5050/prometheus'
